name: docker_package_python3
on:
#  schedule:
#    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}


    - name: Build docker
      run: |
        mv "${GITHUB_WORKSPACE}/resource/python3.11" "${GITHUB_WORKSPACE}/configs/Dockerfile"
        cd "${GITHUB_WORKSPACE}/configs/"
        docker build -t saintvamp/python3:1.0 .
        docker push saintvamp/python3:1.0
        docker build -t saintvamp/python3:latest .
        docker push saintvamp/python3:latest

