name: docker_pack
on:
#  schedule:
#    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}


    - name: Build docker
      run: |
        cd "${GITHUB_WORKSPACE}"
        cd blossom-backend/backend/src/main/resources/static/editor
        rm -rf assets/
        rm favicon.png
        rm index.html
        cd ../../../../../../../blossom-editor
        npm install
        npm run build
        cp -r out/renderer/assets/ ../blossom-backend/backend/src/main/resources/static/editor/
        cp out/renderer/favicon.png ../blossom-backend/backend/src/main/resources/static/editor/
        cp out/renderer/index.html ../blossom-backend/backend/src/main/resources/static/editor/
        cd ../blossom-web
        npm install
        npm run build:spring
        cd ../blossom-backend
        mvn clean
        mvn package
        cd ..
        docker rmi saintvamp/blossom:latest
        docker build -t saintvamp/blossom:latest -f docker/build/Dockerfile .
        docker push saintvamp/blossom:latest


